[package]
name = "handlers"
version = "0.1.0"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
codec.workspace = true
futures.workspace = true
tokio = "1.37.0"

[lints]
workspace = true
