[workspace]
resolver = "2"
members = [
	"utils/*",
	"protocols/*",
	"crypto/falcon/falcon",
	"crypto/*",
	"chat/*",
	"chain/*",
	#"storage/*",
]

exclude = [
	"crypto/falcon",
	"chain/substrate-tests",
]

[workspace.lints.clippy]
all = "warn"
unnecessary_wraps = "warn"
needless_return = "allow"

[workspace.package]
repository = "https://github.com/jakubDoka/orion-network"
readme = "README.md"
keywords = ["network", "decentralized", "polkadot", "pqc"]
categories = ["networking", "cryptography", "blockchain"]
license = "MIT"
edition = "2021"

[workspace.dependencies]
libp2p = "0.53.2"
log = "0.4.20"
futures = "0.3.30"
anyhow = "1.0.80"
thiserror = "1.0.58"
arrayvec = "0.7.4"
kyber = { package = "pqc_kyber", version = "0.7.1" }

dht = { path = "protocols/dht" }
onion = { path = "protocols/onion" }
streaming = { path = "protocols/streaming" }
topology-wrapper = { path = "protocols/topology-wrapper" }

chat-client-node = { path = "chat/client-node", default-features = false }
chat-spec = { path = "chat/spec" }
crypto = { path = "crypto/crypto", features = ["codec"] }
falcon = { path = "crypto/falcon/falcon" }
opfusk = { path = "crypto/opfusk" }
double-ratchet = { path = "crypto/double-ratchet" }
merkle-tree = { path = "crypto/merkle-tree" }

codec-derive = { path = "utils/codec-derive" }
codec = { path = "utils/codec" }
component-utils = { path = "utils/component-utils" }
handlers = { path = "utils/handlers" }
websocket-websys = { path = "utils/websocket-websys" }

chain-api = { path = "chain/api", default-features = false }
chain-api-spec = { path = "chain/api-spec" }
chain-types = { path = "chain/types", default-features = false }
storage-spec = { path = "storage/spec" }
berkleamp-welch = { path = "storage/berkleamp-welch" }

[profile.native-optimized]
inherits = "release"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[profile.dev.package.falcon]
overflow-checks = false
opt-level = 3

[profile.dev.package.argon2]
opt-level = 3

