[package]
name = "codec"
version = "0.1.0"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
arrayvec = { version = "0.7.4", default-features = false, optional = true }
codec-derive = { workspace = true, optional = true }

[lints]
workspace = true

[features]
default = ["derive", "std", "arrayvec"]
std = ["arrayvec/std"]
derive = ["codec-derive"]
